version: '3.1'

services:
  logstash:
    restart: always
    image: logstash:2
    volumes:
          - ./:/config
    command: logstash -f /config/logstash.conf
  elasticsearch:
    restart: always
    image: elasticsearch:2
    ports: 
     - "9200:9200"
  kibana: 
    restart: always
    image: kibana:4
    ports: 
     - "5601:5601"
    links: 
     - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
         - elasticsearch
   myjenkins: 
    image: kayan/myjenkins:latest
    ports: 
     - "8082:8080"
    volumes: 
     - "./jobs:/var/jenkins_home/jobs/"
     - "./m2deps:/var/jenkins_home/.m2/repository/" 
